version: "3.2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  shortener:
    image: "local:latest"
    environment:
      - REDIS_REPLICATION_MODE=master
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "6565:6565"
    depends_on:
      - redis