version: "3.2"
services:

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379