// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shortener.proto

package org.example.tinurl.backend;

public interface GetMaxiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.tinurl.backend.GetMaxiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string original_url = 1;</code>
   */
  java.lang.String getOriginalUrl();
  /**
   * <code>string original_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getOriginalUrlBytes();
}
