// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shortener.proto

package org.example.tinurl.backend;

public interface GetMiniResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.tinurl.backend.GetMiniResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string minified_url = 1;</code>
   */
  java.lang.String getMinifiedUrl();
  /**
   * <code>string minified_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getMinifiedUrlBytes();
}
