// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shortener.proto

package org.example.tinurl.backend;

public final class Shortener {
  private Shortener() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_tinurl_backend_GetMiniRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_tinurl_backend_GetMiniRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_tinurl_backend_GetMiniResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_tinurl_backend_GetMiniResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_tinurl_backend_GetMaxiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_tinurl_backend_GetMaxiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_tinurl_backend_GetMaxiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_tinurl_backend_GetMaxiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017shortener.proto\022\032org.example.tinurl.ba" +
      "ckend\"&\n\016GetMiniRequest\022\024\n\014original_url\030" +
      "\001 \001(\t\"\'\n\017GetMiniResponse\022\024\n\014minified_url" +
      "\030\001 \001(\t\"&\n\016GetMaxiRequest\022\024\n\014minified_url" +
      "\030\001 \001(\t\"\'\n\017GetMaxiResponse\022\024\n\014original_ur" +
      "l\030\001 \001(\t2\330\001\n\016TinyUrlService\022b\n\007GetMini\022*." +
      "org.example.tinurl.backend.GetMiniReques" +
      "t\032+.org.example.tinurl.backend.GetMiniRe" +
      "sponse\022b\n\007GetMaxi\022*.org.example.tinurl.b" +
      "ackend.GetMaxiRequest\032+.org.example.tinu" +
      "rl.backend.GetMaxiResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_example_tinurl_backend_GetMiniRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_tinurl_backend_GetMiniRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_tinurl_backend_GetMiniRequest_descriptor,
        new java.lang.String[] { "OriginalUrl", });
    internal_static_org_example_tinurl_backend_GetMiniResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_tinurl_backend_GetMiniResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_tinurl_backend_GetMiniResponse_descriptor,
        new java.lang.String[] { "MinifiedUrl", });
    internal_static_org_example_tinurl_backend_GetMaxiRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_tinurl_backend_GetMaxiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_tinurl_backend_GetMaxiRequest_descriptor,
        new java.lang.String[] { "MinifiedUrl", });
    internal_static_org_example_tinurl_backend_GetMaxiResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_tinurl_backend_GetMaxiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_tinurl_backend_GetMaxiResponse_descriptor,
        new java.lang.String[] { "OriginalUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
