name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
#       checkout
      - uses: actions/checkout@v1
      - name: set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

#       build project and run all tests & checks
      - name: Gragle build
        run: ./gradlew clean build
