name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Gragle build and run tests
        run: ./gradlew clean build

      - name: Run integration tests
        run: ./gradlew integrationTest